In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,220.0411,8.972,1545
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,67.3993,8.721,30472
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,43.1833,8.700,22980
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,248.9187,8.655,4570
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.5324,8.600,13931

In [4]:
df = pd.DataFrame()

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [11]:
# Loop through all pages of movie data
for i in range(1, 429):

    # Send request to TMDB API
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=d0dfd261b932115b6f3b202ad86004fd&language=en-US&page={i}'
)

    # Convert JSON data to DataFrame
    temp_df = pd.DataFrame(response.json()['results'])

    # Keep only required columns
    temp_df = temp_df[['id','title','overview',
                       'release_date','popularity',
                       'vote_average','vote_count']]

    # Add current page data to main DataFrame
    df = pd.concat([df, temp_df], ignore_index=True)

# Faster Version

In [19]:
# Loop through all pages of movie data
for i in range(1, 429):

    # Send request to TMDB API
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=d0dfd261b932115b6f3b202ad86004fd&language=en-US&page={i}')

    # Convert JSON data to DataFrame
    temp_df = pd.DataFrame(response.json()['results'])

    # Keep only required columns
    temp_df = temp_df[['id','title','overview',
                       'release_date','popularity',
                       'vote_average','vote_count']]

    # Add current page data to main DataFrame
    df = pd.concat([df, temp_df], ignore_index=True)

In [17]:

df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,220.0411,8.972,1545
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,67.3993,8.721,30472
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,43.1833,8.700,22980
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,248.9187,8.655,4570
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.5324,8.600,13931
...,...,...,...,...,...,...,...
8555,328595,Parallels,An underground MMA fighter must confront his s...,2015-03-01,1.2314,6.000,390
8556,209355,The French Minister,Alexandre Taillard de Vorms is a force to be r...,2013-11-06,0.6382,6.028,302
8557,13654,101 Dalmatians II: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",2003-03-02,3.7056,6.028,1239
8558,10547,The Arrival,Zane Ziminski is an astrophysicist who receive...,1996-05-31,2.8205,6.028,835
8559,11834,Jabberwocky,"After the death of his father, young Dennis Co...",1977-03-28,1.5578,6.027,316

In [20]:
df.shape

(17120, 7)

In [21]:
df.to_csv('movies.csv')